language: python
python:
  - "2.7"
install:
  - sudo apt-get update
  - sudo apt-get install python-setuptools  cmake build-essential ninja-build python-dev libffi-dev libssl-dev && sudo easy_install pip
  - sudo apt-get install gcc-arm-none-eabi
  - sudo apt-get install software-properties-common
  - sudo apt-get install cmake
  - sudo ln -s /usr/lib/arm-none-eabi/include/c++/4.9 /usr/lib/arm-none-eabi/include/c++/4.9.3
  - pip install yotta
  
script: yotta build
